[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NEXT_TELEMETRY_DISABLED = "1"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "https://datasourceinc.com/*"
  to = "https://www.datasourceinc.com/:splat"
  status = 301
  force = true
